import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/globals.css";
import Header from "@/ui/Header";
import HeaderBottom from "@/ui/HeaderBottom";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Star Tech - Leading Computer, Laptop & Gadget Shop in Bangladesh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <HeaderBottom />

        {children}
      </body>
    </html>
  );
}
